function init(self)
	msg.post(".", "acquire_camera_focus")
end

function final(self)
	msg.post(".", "release_camera_focus")
end

function update(self, dt)
	local newpos = go.get_position("/player")
	local rotation = go.get_rotation("/player")
	go.animate("/cam_rot", "position", go.PLAYBACK_ONCE_FORWARD, newpos, go.EASING_LINEAR, 0.05)
	go.animate("/cam_rot", "rotation", go.PLAYBACK_ONCE_FORWARD, rotation, go.EASING_LINEAR, 0.2)
end
